#!/usr/bin/env python3
"""
Audit how much of the Aṅguttara Nikāya is published, and write it down.

Compares the pages in discourses/anguttara-nikaya against the source files in
bilara-data, one page per source file. Reports per nipāta: how many are needed,
how many exist, which are missing, and whether the finished stretch has holes
in it. Writes the same table to PROGRESS.md so the state of the project lives
in the repository rather than in whoever happens to be working on it.

    python3 scripts/an_progress.py            # print and rewrite PROGRESS.md
    python3 scripts/an_progress.py --check    # print only, exit 1 if a hole
"""
import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, "discourses", "anguttara-nikaya")
BILARA = os.path.expanduser(
    "~/Documents/Claude/repos/bilara-data/translation/en/sujato/sutta/an")
PROGRESS = os.path.join(OUT_DIR, "PROGRESS.md")


def sort_key(slug):
    """an-3.15 -> (3, 15); an-1.11-20 -> (1, 11)."""
    nums = re.findall(r"\d+", slug.split("-", 1)[1])
    return (int(nums[0]), int(nums[1]) if len(nums) > 1 else 0)


def ranges(numbers):
    if not numbers:
        return "—"
    out, start, prev = [], numbers[0], numbers[0]
    for n in numbers[1:]:
        if n == prev + 1:
            prev = n
        else:
            out.append((start, prev))
            start = prev = n
    out.append((start, prev))
    return ", ".join("%d–%d" % r if r[0] != r[1] else str(r[0]) for r in out)


def survey(nipata):
    """Which pages this nipāta needs, and which exist."""
    needed = set()
    for path in glob.glob(os.path.join(BILARA, "an%d" % nipata, "*.json")):
        uid = os.path.basename(path).split("_")[0]        # an3.15 / an1.11-20
        needed.add("an-" + uid[2:])
    present = set(f[:-5] for f in os.listdir(OUT_DIR)
                  if f.startswith("an-%d." % nipata) and f.endswith(".html"))
    return needed, present


def leading_run(needed, present):
    """How far the finished stretch reaches from the start, and any holes in it."""
    order = sorted(needed, key=sort_key)
    run = []
    for slug in order:
        if slug not in present:
            break
        run.append(slug)
    return run


def main():
    rows, holes = [], []
    total_needed = total_present = 0
    for n in range(1, 12):
        needed, present = survey(n)
        missing = sorted(needed - present, key=sort_key)
        stray = sorted(present - needed, key=sort_key)
        run = leading_run(needed, present)
        ahead = sorted(present & needed - set(run), key=sort_key)
        total_needed += len(needed)
        total_present += len(needed) - len(missing)
        rows.append(dict(n=n, needed=len(needed), have=len(needed) - len(missing),
                         missing=missing, run=run, ahead=ahead, stray=stray))
        if stray:
            holes.append("AN %d: pages with no source file: %s" % (n, stray))

    width = "%-7s %8s %8s %8s   %s"
    print(width % ("nipāta", "needed", "live", "missing", "done in order"))
    print("-" * 76)
    for r in rows:
        done = "%s … %s" % (r["run"][0][3:], r["run"][-1][3:]) if r["run"] else "—"
        print(width % ("AN %d" % r["n"], r["needed"], r["have"],
                       len(r["missing"]), done))
    print("-" * 76)
    print(width % ("total", total_needed, total_present,
                   total_needed - total_present, ""))

    lines = ["# Aṅguttara Nikāya — publishing progress", "",
             "Generated by `python3 scripts/an_progress.py`. One page per",
             "bilara-data source file; the Ones and Twos publish a chapter to a",
             "page, the Threes onward one discourse to a page.", "",
             "| Nipāta | Needed | Live | Missing | Done in order | Next |",
             "|---|---:|---:|---:|---|---|"]
    for r in rows:
        done = "%s–%s" % (r["run"][0][3:], r["run"][-1][3:]) if r["run"] else "—"
        nxt = r["missing"][0][3:] if r["missing"] else "**complete**"
        lines.append("| AN %d | %d | %d | %d | %s | %s |"
                     % (r["n"], r["needed"], r["have"], len(r["missing"]),
                        done, nxt))
    lines += ["| **Total** | **%d** | **%d** | **%d** | | |"
              % (total_needed, total_present, total_needed - total_present), ""]

    for r in rows:
        if not r["missing"]:
            continue
        nums = [sort_key(s)[1] for s in r["missing"]]
        lines += ["## AN %d — %d still to do" % (r["n"], len(r["missing"])), "",
                  "Missing: %s" % ranges(sorted(nums)), ""]
        if r["ahead"]:
            lines += ["Already published out of order (pre-existing pages): %s"
                      % ", ".join(s[3:] for s in r["ahead"]), ""]

    with open(PROGRESS, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print("\nwrote %s" % os.path.relpath(PROGRESS, ROOT))

    if holes:
        print("\nPROBLEMS:")
        for h in holes:
            print("  -", h)
        sys.exit(1)
    print("no pages without a source file; every finished stretch is unbroken")


if __name__ == "__main__":
    main()
