# -*- coding: utf-8 -*-
"""Mahāvagga — The Great Book (SN 45-56). One discourse per page, with
merged pages for peyyāla (formula-repetition) ranges wherever
bilara-data itself stores them as a single file."""

SC = "https://suttacentral.net"

INDEX_HEADING = "V. Mahāvagga — The Great Book"
# Four pages from the original twenty-page curated selection fall
# within this book's own range (SN 45-56): SN 45.8 (Vibhaṅgasutta,
# "Analysis"), SN 55.1 (Cakkavattirājasutta, "A Wheel-Turning
# Monarch"), SN 56.11 (Dhammacakkappavattanasutta, "Rolling Forth the
# Wheel of Dhamma"), and SN 56.31 (Siṁsapāsutta, "In a Rosewood
# Forest") -- confirmed by listing every already-published sn-4[5-9]
# and sn-5[0-6] file directly rather than assumed from Book IV's own
# four-page count. SN 56.31 is this book's own final page: its
# already-built "next" link points to "./" (the collection index),
# confirming it closes the entire original twenty-page curated
# selection -- no further pre-existing page exists anywhere beyond it.
# Registered here in INDEX_EXTRA and not generated by this module; SN
# 45.8 sits mid-vagga inside Avijjāvagga (SN 45.1-10, position 8 of
# 10) and will need the same "fragile junction" treatment Books
# II-IV's own already discovered (SN 12.15, SN 22.59, SN 35.28, SN
# 36.6, SN 41.1, SN 42.8, and others): once Avijjāvagga is generated,
# sn_build.py's auto-chain will skip straight over SN 45.8's own
# pre-existing page, and its neighbours' prev/next must be hand-patched
# after every single build of this module from that point on.
#
# Systematic coverage of this book starts at SN 45.1, the first
# discourse of Avijjāvagga, this saṃyutta's own first vagga. HEAD is
# the nearest already-published page immediately before this module's
# first new page -- SN 44.11, this project's own closing discourse of
# Book IV (Saḷāyatanavagga), whose own "next" link (a static field
# baked into its already-built HTML file) still points to SN 45.8, the
# old placeholder hand-off target from before this module began. SN
# 44.11's own next must be hand-edited once, right now, to point to SN
# 45.1 -- the same one-time fix every earlier book's own HEAD page
# received when that book began.
#
# TAIL points at the nearest already-published page beyond whatever
# this module currently covers -- moved forward as later vaggas are
# completed, exactly as every earlier book's own TAIL was moved across
# its own course. It started at SN 45.8, the nearest already-published
# page beyond nothing yet generated; now that Avijjāvagga (SN 45.1-10,
# including SN 45.8 itself, mid-vagga) is fully generated, SN 45.8 is
# absorbed into this module's own PAGES sequence (hand-patched, not
# auto-chained -- see the fragile-junction note above) and TAIL moves
# to SN 55.1, the next already-published page beyond this module's own
# current coverage -- there being no pre-existing page anywhere within
# SN 45.11-54's own range, confirmed by the directory listing above.
HEAD = ("sn-44.11.html", "SN 44.11 &middot; With Sabhiya Kacc&#257;na")
TAIL = ("sn-55.1.html", "SN 55.1 &middot; A Wheel-Turning Monarch")
INDEX_EXTRA = [
    ("sn-45.8", "Vibhaṅga", "Analysis"),
    ("sn-55.1", "Cakkavattirāja", "A Wheel-Turning Monarch"),
    ("sn-56.11", "Dhammacakkappavattana", "Rolling Forth the Wheel "
                 "of Dhamma"),
    ("sn-56.31", "Siṁsapā", "In a Rosewood Forest"),
]

# --------------------------------------------------------------------------- #
# SN 45 (Maggasaṃyutta, "Linked Discourses on the Path") is this
# book's first saṃyutta, confirmed against both bilara-data's own file
# layout and SuttaCentral's own menu API -- both agree exactly: 180
# discourses across 14 vaggas, but only 114 bilara-data files total
# (confirmed by directly listing the directory), meaning the great
# majority of this saṃyutta's own 180 numbered discourses are stored
# as merged peyyāla ranges rather than individual files -- the
# opposite pattern from Book IV's own SN 43, where a large discourse
# count was matched by a small vagga count; here a large discourse
# count is spread across fourteen vaggas, most of which (from
# Aññatitthiyapeyyālavagga at SN 45.41 onward, per SuttaCentral's own
# vagga breakdown) are explicitly named "peyyāla" vaggas in their own
# Pāli titles:
#
#   1.  Avijjāvagga                    SN 45.1-10   (10) -- contains
#                                                     the pre-existing
#                                                     SN 45.8
#   2.  Vihāravagga                     SN 45.11-20  (10)
#   3.  Micchattavagga                  SN 45.21-30  (10)
#   4.  Paṭipattivagga                  SN 45.31-40  (10)
#   5.  Aññatitthiyapeyyālavagga        SN 45.41-48  (8)
#   6.  Sūriyapeyyālavagga              SN 45.49-62  (14)
#   7.  Ekadhammapeyyālavagga           SN 45.63-76  (14)
#   8.  Dutiyaekadhammapeyyālavagga     SN 45.77-90  (14)
#   9.  Gaṅgāpeyyālavagga               SN 45.91-102 (12)
#   10. Dutiyagaṅgāpeyyālavagga         SN 45.103-138 (36)
#   11. Appamādapeyyālavagga            SN 45.139-148 (10)
#   12. Balakaraṇīyavagga               SN 45.149-160 (12)
#   13. Esanāvagga                      SN 45.161-170 (10)
#   14. Oghavagga                       SN 45.171-180 (10)
#
# Total: 10+10+10+10+8+14+14+14+12+36+10+12+10+10=180, confirmed
# against SuttaCentral's own total_discourses figure. Each vagga's own
# internal structure (individual files vs merged peyyāla ranges) must
# still be confirmed independently before writing it, exactly as every
# earlier saṃyutta's own vaggas required -- do not assume any later
# vagga in this list repeats an earlier one's own shape, and do not
# assume the vagga-6-onward "peyyāla"-named vaggas are uniformly
# structured just because they share that word in their own Pāli
# titles.
# --------------------------------------------------------------------------- #

# --------------------------------------------------------------------------- #
# Avijjāvagga (SN 45.1-10, "The Chapter on Ignorance") is this
# saṃyutta's own first vagga, confirmed by direct reading to be all
# ten individual files, no peyyāla merges -- SN 45.8 (already
# published) sits at position 8 of 10. Structurally this vagga is a
# loose, thematically varied opening rather than one uniform template:
# SN 45.1 states the causal chain from ignorance through the eight
# wrong factors, mirrored by the identical chain from knowledge
# through the eight right factors; SN 45.2-3 are a matched pair on
# spiritual friendship -- the well-known "Upaḍḍha Sutta" -- Ānanda's
# own claim that good friends are "half the spiritual life" corrected
# by the Buddha to "the whole", then Sāriputta independently arriving
# at the Buddha's own corrected formula unprompted and being praised
# for it, confirmed by reading both discourses directly rather than
# assumed to be simple duplicates; SN 45.4 gives the well-known
# "divine vehicle" simile in both prose and a closing verse, the
# eightfold path recast as a chariot Ānanda is shown after seeing a
# brahmin's own literal one; SN 45.5-7 are three short catechisms on
# what the spiritual life is for, each ending in the eightfold path
# named as the answer; SN 45.8 (already published) gives the
# eightfold path's own factor-by-factor formula in full; SN 45.9 uses
# a rice-spike simile for right view pointing the correct or the wrong
# way; SN 45.10 closes the vagga with the wanderer Nandiya's own
# question and this vagga's own untranslated meta-uddāna and closing
# colophon ("Avijjāvaggo paṭhamo").
# --------------------------------------------------------------------------- #

PAGES = []


def page(samyutta, num, pali, title, **kw):
    """Shared scaffolding for a single discourse of Mahāvagga.

    Same two-parameter signature as every earlier book's own page()
    (samyutta, then discourse number), since this book spans several
    independently numbered saṃyuttas (SN 45, 46, 47...) just as Books
    I-IV did.
    """
    d = {
        "slug": "sn-%d.%d" % (samyutta, num),
        "index_pali": pali,
        "nav_title": title,
        "source": "sn%d/sn%d.%d" % (samyutta, samyutta, num),
        "crumb": "SN %d.%d" % (samyutta, num),
        "number_line": "Saṃyutta Nikāya &middot; Discourse %d.%d" % (samyutta, num),
        "title": title,
        "subtitle": "<em>%ssutta</em>%s" % (
            pali, " &mdash; %s" % kw.pop("vagga") if "vagga" in kw else ""),
    }
    d.update(kw)
    PAGES.append(d)
    return d


def page_range(samyutta, lo, hi, pali, title, **kw):
    """Scaffolding for a single page covering a merged range of discourse
    numbers (a peyyāla block bilara-data itself stores as one file)."""
    d = {
        "slug": "sn-%d.%d-%d" % (samyutta, lo, hi),
        "index_pali": pali,
        "nav_title": title,
        "source": "sn%d/sn%d.%d-%d" % (samyutta, samyutta, lo, hi),
        "crumb": "SN %d.%d&ndash;%d" % (samyutta, lo, hi),
        "number_line": "Saṃyutta Nikāya &middot; Discourses %d.%d&ndash;%d" % (samyutta, lo, hi),
        "title": title,
        "subtitle": "<em>%ssutta</em>%s" % (
            pali, " &mdash; %s" % kw.pop("vagga") if "vagga" in kw else ""),
    }
    d.update(kw)
    PAGES.append(d)
    return d
# --------------------------------------------------------------------------- #
# SN 45.1 — Avijjāsutta
# --------------------------------------------------------------------------- #
page(
    45, 1, "Avijjā", "Ignorance",
    vagga="Avijjāvagga",
    meta_title="SN 45.1 — Ignorance | Ru-Yi Meditation Center",
    meta_desc=(
        "A reading guide, full English text, and self-check quiz for "
        "the Avijjāsutta &mdash; opening Book V with two mirrored "
        "causal chains, ignorance producing the eight wrong factors, "
        "knowledge producing the eight right ones. From Ru-Yi "
        "Meditation Center."),
    glance=[
        ("Setting", "Sāvatthī, Jeta's Grove, Anāthapiṇḍika's "
                     "monastery"),
        ("Speakers", "The Buddha, addressing the mendicants directly"),
        ("Form", "Two mirrored nine-step causal chains, opening this "
                 "book's own first saṃyutta"),
        ("Length", "~1 minute to read"),
        ("Northern parallel", "No individual parallel confirmed by "
                              "this project's own check"),
        ("Difficulty", "&starf;&#9734;&#9734;&#9734;&#9734; &mdash; "
                       "short, two clear parallel chains"),
    ],
    why=(
        "This discourse opens Book V (Mahāvagga, the Great Book, SN "
        "45&ndash;56) with a causal chain this project has not seen "
        "stated quite this way before: ignorance itself, not merely "
        "one factor among others, is named as what precedes and "
        "produces wrong view, which in turn produces each of the "
        "remaining seven wrong factors of the eightfold path in "
        "strict sequence &mdash; and the identical chain, reversed, "
        "runs from knowledge through all eight right factors. The "
        "eightfold path itself, this book's own governing framework, "
        "is presented here as something that can run in either "
        "direction depending on what precedes it."
    ),
    guide=[
        ("One chain running backward through the path", [
            "Wrong view produces wrong purpose, which produces wrong "
            "speech, then wrong action, wrong livelihood, wrong "
            "effort, wrong mindfulness, and finally wrong immersion "
            "&mdash; each of the eightfold path's own eight factors "
            "named in exactly its usual order, but here as a chain "
            "of causation rather than a list of virtues to cultivate.",
        ]),
        ("Ignorance and knowledge as what starts each chain", [
            "Ignorance itself &ldquo;precedes the attainment of "
            "unskillful qualities,&rdquo; with lack of conscience and "
            "prudence following along before wrong view even arises "
            "&mdash; and knowledge precedes skillful qualities the "
            "identical way, confirmed by reading both halves of this "
            "discourse directly: not simply &ldquo;ignorance is bad, "
            "knowledge is good,&rdquo; but a specific claim about "
            "what comes first in each causal sequence.",
        ]),
    ],
    terms=[
        ("avijjā", "&ldquo;ignorance&rdquo; &mdash; what this "
             "discourse names as preceding the entire chain of eight "
             "wrong factors, giving this discourse and its own vagga "
             "their shared name"),
        ("micchādiṭṭhi", "&ldquo;wrong view&rdquo; &mdash; the first "
             "link the chain of ignorance produces, itself producing "
             "each of the remaining seven wrong factors in turn"),
        ("ahirikaṁ anottappaṁ", "&ldquo;lack of conscience and "
             "prudence&rdquo; &mdash; what this discourse says "
             "follows along with ignorance, before wrong view itself "
             "arises"),
        ("vijjā", "&ldquo;knowledge&rdquo; &mdash; the mirrored "
             "starting point of this discourse's own second chain, "
             "producing right view and, through it, all eight right "
             "factors"),
        ("sammādiṭṭhi... sammāsamādhi", "&ldquo;right view... right "
             "immersion&rdquo; &mdash; the eightfold path's own eight "
             "factors, named here as the final links of the "
             "knowledge-based chain"),
    ],
    text_intro=("The complete discourse. Translation: Bhikkhu Sujato "
        "(CC0, SuttaCentral)."),
    text=[
        ("h3", "Setting"),
        ("p", "&sect;1", "sn45.1:1.1-1.6"),
        ("h3", "Ignorance, and the chain of eight wrong factors"),
        ("p", "&sect;2", "sn45.1:2.1-2.9"),
        ("h3", "Knowledge, and the chain of eight right factors"),
        ("p", "&sect;3", "sn45.1:3.1-3.9"),
    ],
    quiz=[
        {"q": "What does this discourse say precedes the attainment of unskillful qualities?",
         "opts": ["Ignorance", "Wrong view directly, with nothing preceding it", "Old age", "Bad company"],
         "correct": 0,
         "expl": "Ignorance itself, with lack of conscience and prudence following along, before wrong view even arises."},
        {"q": "In what order does the chain of wrong factors unfold, according to this discourse?",
         "opts": ["Wrong view, purpose, speech, action, livelihood, effort, mindfulness, immersion — in that sequence", "All eight factors arise simultaneously", "Wrong immersion first, working backward to wrong view", "Only wrong view is mentioned; the rest are omitted"],
         "correct": 0,
         "expl": "Each factor of the eightfold path named in exactly its usual order, but as a strict causal chain rather than a list."},
        {"q": "What is the mirrored starting point of the second, positive chain?",
         "opts": ["Knowledge", "Faith", "Meditation", "Generosity"],
         "correct": 0,
         "expl": "Knowledge precedes right view, which produces all eight right factors, the identical structure as the ignorance-based chain."},
    ],
    marginalia=[
        ("A book opens with causation", [
            "ignorance, then eight wrong factors —",
            "the path itself, running backward",
        ]),
        ("What comes before wrong view", [
            "no conscience, no prudence —",
            "ignorance already at work",
        ]),
        ("The mirrored chain", [
            "knowledge, then eight right factors —",
            "the identical sequence, reversed",
        ]),
        ("This vagga's own name, explained", [
            "Avijjāvagga — \"ignorance\" —",
            "named for this opening discourse itself",
        ]),
    ],
    further=[
        '<a href="%s/sn45.1/en/sujato" target="_blank" rel="noopener">'
        "Full Sujato translation on SuttaCentral</a> &mdash; with "
        "Pāli alongside, segment by segment."
        % SC,
        "<a href=\"sn-44.11.html\">SN 44.11 &middot; With Sabhiya "
        "Kaccāna</a> &mdash; the previous discourse, closing Book IV.",
        "<a href=\"sn-45.2.html\">SN 45.2 &middot; Half the "
        "Spiritual Life</a> &mdash; the next discourse.",
    ],
)

# --------------------------------------------------------------------------- #
# SN 45.2 — Upaḍḍhasutta
# --------------------------------------------------------------------------- #
page(
    45, 2, "Upaḍḍha", "Half the Spiritual Life",
    vagga="Avijjāvagga",
    meta_title="SN 45.2 — Half the Spiritual Life | Ru-Yi Meditation Center",
    meta_desc=(
        "A reading guide, full English text, and self-check quiz for "
        "the Upaḍḍhasutta &mdash; the well-known discourse where the "
        "Buddha corrects Ānanda: good friends are not half the "
        "spiritual life but the whole of it. From Ru-Yi Meditation "
        "Center."),
    glance=[
        ("Setting", "Townsville, in the land of the Sakyans"),
        ("Speakers", "Venerable Ānanda and the Buddha"),
        ("Form", "A disciple's claim, corrected and then explained "
                 "two ways"),
        ("Length", "~1 minute to read"),
        ("Northern parallel", "SA 726 and SA 768, both classified as "
                              "full parallels by SuttaCentral's own "
                              "parallels record"),
        ("Difficulty", "&starf;&#9734;&#9734;&#9734;&#9734; &mdash; "
                       "short, a well-known and easily stated point"),
    ],
    why=(
        "One of the most quoted discourses in the early texts: Ānanda "
        "offers what sounds like a generous claim &mdash; good "
        "friends, companions, and associates are &ldquo;half the "
        "spiritual life&rdquo; &mdash; and the Buddha corrects him "
        "twice over, emphatically: &ldquo;not so.&rdquo; They are, he "
        "says, &ldquo;the whole of the spiritual life,&rdquo; and "
        "gives two independent reasons why, the first practical (good "
        "friendship supports developing the eightfold path) and the "
        "second startlingly direct (the Buddha names himself as the "
        "&ldquo;good friend&rdquo; by whom beings are freed)."
    ),
    guide=[
        ("A generous claim, corrected as insufficient", [
            "&ldquo;Not so, Ānanda! Not so, Ānanda!&rdquo; &mdash; "
            "repeated for emphasis, confirmed by reading the source "
            "directly rather than softened in translation &mdash; "
            "Ānanda's own claim is not wrong so much as too modest: "
            "good friendship is not one contributing factor among "
            "others but the entire practice.",
        ]),
        ("Two independent reasons, not one elaborated", [
            "The first reason is structural: a mendicant with good "
            "friends can be expected to develop the eightfold path, "
            "each factor spelled out in turn; the second is "
            "personal and direct &mdash; by relying on the Buddha "
            "himself as a good friend, beings are freed from "
            "rebirth, old age, and death &mdash; confirmed by "
            "reading the discourse's own explicit &ldquo;here's "
            "another way to understand&rdquo; transition marking "
            "these as two separate arguments, not one continuous "
            "explanation.",
        ]),
        ("This discourse's own companion, immediately following", [
            "SN 45.3, read alongside this discourse, shows Sāriputta "
            "independently arriving at the Buddha's own corrected "
            "formula &mdash; &ldquo;the whole of the spiritual "
            "life&rdquo; &mdash; without having heard this "
            "conversation, and being praised for it rather than "
            "corrected, confirming the point is not particular to "
            "Ānanda's own error but a genuine teaching two different "
            "disciples are shown testing against.",
        ]),
    ],
    terms=[
        ("kalyāṇamittatā", "&ldquo;good friends, companions, and "
             "associates&rdquo; &mdash; the quality this discourse's "
             "own central claim concerns, sometimes rendered "
             "&ldquo;spiritual friendship&rdquo;"),
        ("upaḍḍhamidaṁ brahmacariyaṁ", "&ldquo;half the spiritual "
             "life&rdquo; &mdash; Ānanda's own original claim, "
             "corrected by the Buddha"),
        ("sakalamevidaṁ brahmacariyaṁ", "&ldquo;the whole of the "
             "spiritual life&rdquo; &mdash; the Buddha's own "
             "corrected formula, repeated at both of this "
             "discourse's own closing arguments"),
        ("kalyāṇamitte āgamma... ariyaṁ aṭṭhaṅgikaṁ maggaṁ",
             "&ldquo;with good friends... the noble eightfold "
             "path&rdquo; &mdash; the first of the two reasons, "
             "linking good friendship structurally to path practice"),
        ("maṁ āgamma kalyāṇamittaṁ", "&ldquo;by relying on me as a "
             "good friend&rdquo; &mdash; the Buddha's own direct, "
             "personal second reason"),
    ],
    text_intro=("The complete discourse. Translation: Bhikkhu Sujato "
        "(CC0, SuttaCentral)."),
    text=[
        ("h3", "Ānanda's own claim, and the Buddha's correction"),
        ("p", "&sect;1", "sn45.2:1.1-2.3"),
        ("h3", "First reason: good friends and the eightfold path"),
        ("p", "&sect;2", "sn45.2:3.1-3.10"),
        ("h3", "Second reason: the Buddha himself as good friend"),
        ("p", "&sect;3", "sn45.2:4.1-4.3"),
    ],
    quiz=[
        {"q": "How does the Buddha respond to Ānanda's claim that good friends are \"half the spiritual life\"?",
         "opts": ["He corrects it emphatically: good friends are the whole of the spiritual life", "He agrees without qualification", "He says good friends are irrelevant to the spiritual life", "He asks Ānanda to consult Sāriputta first"],
         "correct": 0,
         "expl": "\"Not so, Ānanda! Not so, Ānanda!\" — repeated for emphasis, before the corrected formula."},
        {"q": "What is the second, more personal reason the Buddha gives for why good friends are the whole of the spiritual life?",
         "opts": ["By relying on the Buddha himself as a good friend, beings are freed from rebirth, old age, and death", "Because good friends provide material support", "Because the Buddha requires disciples to have friends", "Because friendship prevents loneliness"],
         "correct": 0,
         "expl": "A direct, personal claim, distinct from the structural first reason about developing the eightfold path."},
        {"q": "What does SN 45.3, read alongside this discourse, show?",
         "opts": ["Sāriputta independently arriving at the same corrected formula and being praised for it", "Ānanda repeating his original mistaken claim", "A wanderer disputing the Buddha's own correction", "The Buddha retracting his correction"],
         "correct": 0,
         "expl": "Confirming the point is a genuine teaching, not particular to one disciple's own error."},
    ],
    marginalia=[
        ("A generous claim, still too modest", [
            "\"half the spiritual life\" —",
            "corrected twice, emphatically",
        ]),
        ("Not half, but the whole", [
            "\"not so, Ānanda! Not so!\" —",
            "the corrected formula, repeated",
        ]),
        ("Two reasons, not one", [
            "the path developed through good friends —",
            "and the Buddha himself, the good friend",
        ]),
        ("A companion discourse follows", [
            "Sāriputta, independently, the same formula —",
            "praised, not corrected",
        ]),
    ],
    further=[
        '<a href="%s/sn45.2/en/sujato" target="_blank" rel="noopener">'
        "Full Sujato translation on SuttaCentral</a> &mdash; with "
        "Pāli alongside, segment by segment."
        % SC,
        "<a href=\"sn-45.1.html\">SN 45.1 &middot; Ignorance</a> "
        "&mdash; the previous discourse.",
        "<a href=\"sn-45.3.html\">SN 45.3 &middot; "
        "Sāriputta</a> &mdash; the next discourse, this claim's own "
        "companion piece.",
    ],
)

# --------------------------------------------------------------------------- #
# SN 45.3 — Sāriputtasutta
# --------------------------------------------------------------------------- #
page(
    45, 3, "Sāriputta", "Sāriputta",
    vagga="Avijjāvagga",
    meta_title="SN 45.3 — Sāriputta | Ru-Yi Meditation Center",
    meta_desc=(
        "A reading guide, full English text, and self-check quiz for "
        "the Sāriputtasutta &mdash; Sāriputta independently arriving "
        "at the Buddha's own corrected formula from SN 45.2, and "
        "being praised rather than corrected. From Ru-Yi Meditation "
        "Center."),
    glance=[
        ("Setting", "Not specified beyond this discourse's own "
                     "opening"),
        ("Speakers", "Venerable Sāriputta and the Buddha"),
        ("Form", "The identical claim and structure as SN 45.2, "
                 "compressed and independently offered rather than "
                 "corrected"),
        ("Length", "&lt;1 minute to read"),
        ("Northern parallel", "No individual parallel confirmed by "
                              "this project's own check"),
        ("Difficulty", "&starf;&#9734;&#9734;&#9734;&#9734; &mdash; "
                       "short, a compressed companion to SN 45.2"),
    ],
    why=(
        "Where SN 45.2 shows Ānanda offering the modest claim and "
        "being corrected, this discourse shows Sāriputta arriving at "
        "the Buddha's own corrected formula directly and "
        "unprompted &mdash; &ldquo;good friends, companions, and "
        "associates are the whole of the spiritual life&rdquo; "
        "&mdash; and receiving praise (&ldquo;good, good, "
        "Sāriputta!&rdquo;) rather than any correction at all, "
        "confirming this is a genuine teaching two different senior "
        "disciples are shown testing, not a lesson particular to "
        "Ānanda's own understanding."
    ),
    guide=[
        ("The same claim, offered correctly from the start", [
            "Sāriputta states &ldquo;the whole of the spiritual "
            "life&rdquo; directly, without first offering "
            "&ldquo;half&rdquo; the way Ānanda did &mdash; confirmed "
            "by reading this discourse's own opening exchange "
            "directly, the difference between the two discourses is "
            "not in the final formula but in how each disciple "
            "arrives at it.",
        ]),
        ("Compressed, not merely repeated", [
            "The eightfold path's own eight factors, spelled out one "
            "by one in SN 45.2, are compressed here into a single "
            "run-on list, and the same is true of the closing "
            "&ldquo;another way to understand&rdquo; argument &mdash; "
            "confirmed by direct comparison, this discourse assumes "
            "its own reader already knows the fuller version rather "
            "than restating it at length.",
        ]),
    ],
    terms=[
        ("sakalamevidaṁ brahmacariyaṁ", "&ldquo;the whole of the "
             "spiritual life&rdquo; &mdash; Sāriputta's own claim, "
             "offered directly and confirmed without correction"),
        ("sādhu sādhu, sāriputta", "&ldquo;good, good, "
             "Sāriputta!&rdquo; &mdash; the Buddha's own response, "
             "praise rather than the correction Ānanda received in "
             "SN 45.2"),
        ("kalyāṇamittatā", "&ldquo;good friends, companions, and "
             "associates&rdquo; &mdash; the identical quality both "
             "this discourse and SN 45.2 concern"),
        ("ariyaṁ aṭṭhaṅgikaṁ maggaṁ bhāveti", "&ldquo;develop the "
             "noble eightfold path&rdquo; &mdash; the structural "
             "first reason, compressed here into a single list "
             "rather than SN 45.2's own factor-by-factor treatment"),
        ("maṁ āgamma kalyāṇamittaṁ", "&ldquo;by relying on me as a "
             "good friend&rdquo; &mdash; the second reason, "
             "identical in wording to SN 45.2's own"),
    ],
    text_intro=("The complete discourse. Translation: Bhikkhu Sujato "
        "(CC0, SuttaCentral)."),
    text=[
        ("p", "&sect;1", "sn45.3:1.1-4.3"),
    ],
    quiz=[
        {"q": "How does Sāriputta's own claim in this discourse differ from Ānanda's in SN 45.2?",
         "opts": ["Sāriputta states \"the whole of the spiritual life\" directly, without first offering \"half\"", "Sāriputta claims good friends are irrelevant", "Sāriputta disputes the Buddha's own teaching entirely", "Sāriputta asks a completely unrelated question"],
         "correct": 0,
         "expl": "The difference is in how each disciple arrives at the formula, not in the final formula itself."},
        {"q": "How does the Buddha respond to Sāriputta's claim?",
         "opts": ["With praise — \"good, good, Sāriputta!\" — rather than any correction", "By correcting him the same way he corrected Ānanda", "By ignoring the claim entirely", "By asking Sāriputta to consult Ānanda first"],
         "correct": 0,
         "expl": "Confirming this is a genuine teaching being independently tested by two disciples, not a lesson particular to one disciple's error."},
        {"q": "How does this discourse's own treatment of the eightfold path compare to SN 45.2's own?",
         "opts": ["Compressed into a single run-on list, rather than spelled out factor by factor", "Expanded with additional detail not found in SN 45.2", "Entirely omitted", "Replaced with a different list of qualities"],
         "correct": 0,
         "expl": "This discourse assumes its own reader already knows the fuller version from SN 45.2 rather than restating it at length."},
    ],
    marginalia=[
        ("The same claim, stated directly", [
            "\"the whole of the spiritual life\" —",
            "no correction needed this time",
        ]),
        ("Praise, not correction", [
            "\"good, good, Sāriputta!\" —",
            "the identical formula, differently received",
        ]),
        ("A compressed companion", [
            "the eightfold path, run together —",
            "assuming SN 45.2's own fuller version already known",
        ]),
        ("Two disciples, one teaching", [
            "Ānanda corrected, Sāriputta confirmed —",
            "the same point, tested twice",
        ]),
    ],
    further=[
        '<a href="%s/sn45.3/en/sujato" target="_blank" rel="noopener">'
        "Full Sujato translation on SuttaCentral</a> &mdash; with "
        "Pāli alongside, segment by segment."
        % SC,
        "<a href=\"sn-45.2.html\">SN 45.2 &middot; Half the "
        "Spiritual Life</a> &mdash; the previous discourse, this "
        "claim's own companion piece.",
        "<a href=\"sn-45.4.html\">SN 45.4 &middot; Regarding the "
        "Brahmin Jānussoṇi</a> &mdash; the next discourse, the "
        "well-known \"divine vehicle\" simile.",
    ],
)

# --------------------------------------------------------------------------- #
# SN 45.4 — Jāṇussoṇisutta
# --------------------------------------------------------------------------- #
page(
    45, 4, "Jāṇussoṇi", "Regarding the Brahmin Jānussoṇi",
    vagga="Avijjāvagga",
    meta_title="SN 45.4 — Regarding the Brahmin Jānussoṇi | Ru-Yi Meditation Center",
    meta_desc=(
        "A reading guide, full English text, and self-check quiz for "
        "the Jāṇussoṇisutta &mdash; the well-known \"divine vehicle\" "
        "simile, the eightfold path recast as a chariot in both prose "
        "and closing verse. From Ru-Yi Meditation Center."),
    glance=[
        ("Setting", "Sāvatthī, on Ānanda's own alms round"),
        ("Speakers", "Venerable Ānanda and the Buddha"),
        ("Form", "A vivid secondhand observation, a question, a "
                 "prose answer, and a closing verse"),
        ("Length", "~2 minutes to read"),
        ("Northern parallel", "No individual parallel confirmed by "
                              "this project's own check"),
        ("Difficulty", "&starf;&starf;&#9734;&#9734;&#9734; &mdash; "
                       "a vivid simile, extended into verse"),
    ],
    why=(
        "Ānanda sees a brahmin's own literal chariot &mdash; "
        "brilliant white, drawn by white mares, its every part white "
        "&mdash; and onlookers exclaiming it must be &ldquo;a divine "
        "vehicle.&rdquo; He asks the Buddha whether the teaching "
        "itself has anything to match it, and receives an answer in "
        "two registers: first plain prose naming the noble eightfold "
        "path as exactly this &mdash; &ldquo;divine vehicle,&rdquo; "
        "&ldquo;vehicle of truth,&rdquo; &ldquo;supreme victory in "
        "battle&rdquo; &mdash; then a closing verse building out the "
        "chariot image factor by factor: faith and wisdom yoked to "
        "the shaft, ethics as the chariot itself, energy as its "
        "wheel."
    ),
    guide=[
        ("A literal chariot, admired by a crowd", [
            "The brahmin Jānussoṇi's own chariot is described in "
            "loving, specific detail &mdash; white mares, white "
            "reins, white turban, even a white chowry fanning him "
            "&mdash; the kind of description this project has not "
            "lingered on before, setting up the simile's own "
            "contrast between visible splendor and the path's own "
            "less immediately impressive form.",
        ]),
        ("Three names for one thing, not three different things", [
            "&ldquo;Divine vehicle,&rdquo; &ldquo;vehicle of "
            "truth,&rdquo; and &ldquo;supreme victory in battle&rdquo; "
            "are given as three names the eightfold path already "
            "answers to, not three separate vehicles to compare "
            "&mdash; confirmed by reading the Buddha's own closing "
            "restatement, which repeats all three names together as "
            "one settled point.",
        ]),
        ("The verse extends the metaphor part by part", [
            "Faith and wisdom as the yoke, conscience as the "
            "draft-pole, mindfulness as the driver, ethics as the "
            "chariot itself, energy as the wheel, equanimity and "
            "immersion as a second draft-pole, desirelessness as the "
            "upholstery, good will and harmlessness as weaponry, "
            "endurance as shield and armor &mdash; confirmed by "
            "reading the verse directly rather than assumed to "
            "simply restate the prose, this closing poem maps a "
            "genuinely fuller set of qualities onto the chariot's own "
            "parts than the prose answer names.",
        ]),
    ],
    terms=[
        ("dibbo yāno", "&ldquo;divine vehicle&rdquo; &mdash; the "
             "onlookers' own exclamation about the literal chariot, "
             "and the first of three names the Buddha applies to the "
             "eightfold path"),
        ("dhammayāno", "&ldquo;vehicle of truth&rdquo; &mdash; the "
             "second of the three names"),
        ("anuttaro saṅgāmavijayo", "&ldquo;supreme victory in "
             "battle&rdquo; &mdash; the third name, framing the path "
             "in terms of conquest rather than transport"),
        ("saddhā ca hiri sārathi", "&ldquo;faith... conscience its "
             "draft-pole, mind its strap, mindfulness its careful "
             "driver&rdquo; &mdash; the opening lines of the closing "
             "verse, extending the chariot metaphor part by part"),
        ("sīlaparikkhāro ratho", "&ldquo;the chariot equipped with "
             "ethics&rdquo; &mdash; ethics itself named as the "
             "chariot's own body in the verse's second stanza"),
    ],
    text_intro=("The complete discourse, in both its prose and verse "
        "sections. Translation: Bhikkhu Sujato (CC0, SuttaCentral)."),
    text=[
        ("h3", "A literal chariot, and a question about the teaching"),
        ("p", "&sect;1", "sn45.4:1.1-4.3"),
        ("h3", "The eightfold path, named three ways"),
        ("p", "&sect;2", "sn45.4:5.1-6.3"),
        ("h3", "The closing verse: the path as a chariot, part by "
                "part"),
        ("p", "&sect;3", "sn45.4:7.1-11.4"),
    ],
    quiz=[
        {"q": "What prompts Ānanda's question to the Buddha in this discourse?",
         "opts": ["Seeing a brahmin's own brilliant white chariot, called a \"divine vehicle\" by onlookers", "A dream Ānanda had the previous night", "A direct challenge from a wanderer", "A request from King Pasenadi"],
         "correct": 0,
         "expl": "A vivid, specific secondhand observation on Ānanda's own alms round, setting up the simile that follows."},
        {"q": "What three names does the Buddha apply to the noble eightfold path in this discourse?",
         "opts": ["\"Divine vehicle,\" \"vehicle of truth,\" and \"supreme victory in battle\"", "\"The straight path,\" \"the middle way,\" and \"the noble path\"", "Three different similes for three different audiences", "Only one name — \"divine vehicle\" alone"],
         "correct": 0,
         "expl": "Three names for the same thing, not three separate vehicles — confirmed by the Buddha's own closing restatement."},
        {"q": "What does the closing verse do that the prose answer does not?",
         "opts": ["Maps a fuller set of qualities onto the chariot's own individual parts", "Contradicts the prose answer's own claim", "Introduces an entirely unrelated topic", "Simply repeats the prose answer word for word"],
         "correct": 0,
         "expl": "Faith and wisdom as the yoke, ethics as the chariot itself, energy as the wheel — a genuinely fuller elaboration than the prose alone gives."},
    ],
    marginalia=[
        ("A chariot, admired by a crowd", [
            "white mares, white reins, white turban —",
            "\"a vehicle fit for divinity!\"",
        ]),
        ("Three names, one path", [
            "divine vehicle, vehicle of truth, supreme victory —",
            "not three vehicles, one settled point",
        ]),
        ("A verse builds the metaphor further", [
            "faith and wisdom yoked to the shaft —",
            "ethics itself, the chariot's own body",
        ]),
        ("Splendor recast, not simply matched", [
            "a fuller elaboration than mere comparison —",
            "the path's own genuine equipment, part by part",
        ]),
    ],
    further=[
        '<a href="%s/sn45.4/en/sujato" target="_blank" rel="noopener">'
        "Full Sujato translation on SuttaCentral</a> &mdash; with "
        "Pāli alongside, segment by segment."
        % SC,
        "<a href=\"sn-45.3.html\">SN 45.3 &middot; Sāriputta</a> "
        "&mdash; the previous discourse.",
        "<a href=\"sn-45.5.html\">SN 45.5 &middot; What's the "
        "Goal?</a> &mdash; the next discourse.",
    ],
)

# --------------------------------------------------------------------------- #
# SN 45.5 — Aññatitthiyasutta
# --------------------------------------------------------------------------- #
page(
    45, 5, "Aññatitthiya", "What&rsquo;s the Goal?",
    vagga="Avijjāvagga",
    meta_title="SN 45.5 — What's the Goal? | Ru-Yi Meditation Center",
    meta_desc=(
        "A reading guide, full English text, and self-check quiz for "
        "a discourse teaching mendicants a ready answer when "
        "outsiders ask what the spiritual life under the Buddha is "
        "for. From Ru-Yi Meditation Center."),
    glance=[
        ("Setting", "Sāvatthī"),
        ("Speakers", "Several mendicants and the Buddha"),
        ("Form", "Mendicants report an answer they already trust, "
                 "confirmed and completed by the Buddha"),
        ("Length", "&lt;1 minute to read"),
        ("Northern parallel", "No individual parallel confirmed by "
                              "this project's own check"),
        ("Difficulty", "&starf;&#9734;&#9734;&#9734;&#9734; &mdash; "
                       "short, a rehearsed answer confirmed"),
    ],
    why=(
        "Mendicants report the answer they already give when "
        "outsiders ask what the spiritual life under the Buddha is "
        "for &mdash; &ldquo;to completely understand suffering&rdquo; "
        "&mdash; and, in language this project has met before "
        "(compare SN 44.2's own Anurādha), express their own trust "
        "that this answer genuinely represents the teaching without "
        "misrepresentation. The Buddha confirms it directly, then "
        "supplies the one piece they had not yet been asked for: "
        "the path and practice for that understanding is simply the "
        "eightfold path itself."
    ),
    guide=[
        ("An answer already trusted, checked and confirmed", [
            "The mendicants' own phrasing &mdash; &ldquo;we trust "
            "that we repeat what the Buddha has said, and don't "
            "misrepresent him&rdquo; &mdash; echoes the same careful "
            "concern for accuracy this project met in Anurādha's own "
            "private reflection at SN 44.2, confirmed by direct "
            "comparison of the two discourses' own wording.",
        ]),
        ("One question anticipates the next", [
            "The Buddha's own answer does not stop at confirming "
            "&ldquo;to completely understand suffering&rdquo; "
            "&mdash; he supplies, unprompted, the follow-up question "
            "outsiders would naturally ask next (&ldquo;is there a "
            "path?&rdquo;) and its own answer, equipping the "
            "mendicants for a conversation that has not yet "
            "happened rather than only confirming the one that "
            "already did.",
        ]),
    ],
    terms=[
        ("dukkhassa pariññatthaṁ", "&ldquo;to completely understand "
             "suffering&rdquo; &mdash; the mendicants' own answer to "
             "outsiders' questions, confirmed by the Buddha as "
             "accurate"),
        ("na ca... asatā abbhācikkhāma", "&ldquo;we don't "
             "misrepresent him with an untruth&rdquo; &mdash; the "
             "mendicants' own careful concern for accuracy, echoing "
             "Anurādha's identical concern at SN 44.2"),
        ("atthi maggo atthi paṭipadā", "&ldquo;there is a path and a "
             "practice&rdquo; &mdash; the anticipated follow-up "
             "question and its own confirmed answer"),
        ("ayaṁ ariyo aṭṭhaṅgiko maggo", "&ldquo;this noble eightfold "
             "path&rdquo; &mdash; the specific path named as the "
             "practice for completely understanding suffering"),
        ("aññatitthiyā paribbājakā", "&ldquo;wanderers of other "
             "religions&rdquo; &mdash; the outsiders whose questions "
             "this discourse equips mendicants to answer"),
    ],
    text_intro=("The complete discourse. Translation: Bhikkhu Sujato "
        "(CC0, SuttaCentral)."),
    text=[
        ("p", "&sect;1", "sn45.5:1.1-4.5"),
    ],
    quiz=[
        {"q": "What answer do the mendicants already give when outsiders ask about the goal of the spiritual life under the Buddha?",
         "opts": ["To completely understand suffering", "To attain wealth and status", "To gain magical powers", "To please the gods"],
         "correct": 0,
         "expl": "Confirmed by the Buddha as accurately representing his own teaching."},
        {"q": "What does the Buddha add beyond simply confirming the mendicants' own answer?",
         "opts": ["The anticipated follow-up question about a path, and its own answer", "A correction to their answer", "A request that they stop answering outsiders' questions", "An entirely different topic"],
         "correct": 0,
         "expl": "Equipping the mendicants for a conversation that has not yet happened, not merely confirming the one that already did."},
        {"q": "What path does the Buddha name for completely understanding suffering?",
         "opts": ["The noble eightfold path", "The five faculties", "The seven awakening factors", "A path known only to advanced practitioners"],
         "correct": 0,
         "expl": "The same eightfold path this book's own opening discourses have each returned to."},
    ],
    marginalia=[
        ("An answer already rehearsed", [
            "\"to completely understand suffering\" —",
            "trusted, then confirmed directly",
        ]),
        ("The same careful concern as Anurādha's own", [
            "not to misrepresent with an untruth —",
            "echoed from this project's own SN 44.2",
        ]),
        ("A question anticipated", [
            "\"is there a path?\" — asked before it's asked —",
            "equipped for what comes next",
        ]),
        ("The eightfold path, once more", [
            "the practice for understanding suffering —",
            "this vagga's own recurring answer",
        ]),
    ],
    further=[
        '<a href="%s/sn45.5/en/sujato" target="_blank" rel="noopener">'
        "Full Sujato translation on SuttaCentral</a> &mdash; with "
        "Pāli alongside, segment by segment."
        % SC,
        "<a href=\"sn-45.4.html\">SN 45.4 &middot; Regarding the "
        "Brahmin Jānussoṇi</a> &mdash; the previous discourse.",
        "<a href=\"sn-45.6.html\">SN 45.6 &middot; A Mendicant "
        "(1st)</a> &mdash; the next discourse.",
    ],
)

# --------------------------------------------------------------------------- #
# SN 45.6 — Paṭhamaññatarabhikkhusutta
# --------------------------------------------------------------------------- #
page(
    45, 6, "Aññatarabhikkhu", "A Mendicant (1st)",
    vagga="Avijjāvagga",
    meta_title="SN 45.6 — A Mendicant (1st) | Ru-Yi Meditation Center",
    meta_desc=(
        "A reading guide, full English text, and self-check quiz for "
        "a mendicant's brief question about the spiritual path and "
        "its own culmination, answered in two sentences. From Ru-Yi "
        "Meditation Center."),
    glance=[
        ("Setting", "Sāvatthī"),
        ("Speakers", "An unnamed mendicant and the Buddha"),
        ("Form", "A two-part question, answered in two sentences"),
        ("Length", "&lt;1 minute to read"),
        ("Northern parallel", "No individual parallel confirmed by "
                              "this project's own check"),
        ("Difficulty", "&starf;&#9734;&#9734;&#9734;&#9734; &mdash; "
                       "very short, a direct pair of definitions"),
    ],
    why=(
        "An unnamed mendicant asks the plainest possible question "
        "about this book's own governing term &mdash; what is the "
        "spiritual path, and what is its own culmination &mdash; and "
        "receives an answer that names the eightfold path for the "
        "first question and, for the second, returns to the fixed "
        "definition this project has met defining &ldquo;the "
        "unconditioned&rdquo; throughout SN 43: the ending of greed, "
        "hate, and delusion."
    ),
    guide=[
        ("Two questions, answered in one breath", [
            "&ldquo;What is the spiritual path? And what is the "
            "culmination of the spiritual path?&rdquo; receives two "
            "answers in immediate succession, the path itself named "
            "first and its own endpoint second, with no further "
            "elaboration &mdash; this discourse's own entire content "
            "beyond the setting.",
        ]),
        ("The same closing formula as SN 43's own asaṅkhata", [
            "&ldquo;The ending of greed, hate, and delusion&rdquo; "
            "is confirmed by direct comparison to be the identical "
            "phrase this project's own SN 43 used throughout to "
            "define asaṅkhata, &ldquo;the unconditioned&rdquo; "
            "&mdash; here applied to &ldquo;the culmination of the "
            "spiritual path&rdquo; instead, the same goal reached "
            "through this book's own different vocabulary.",
        ]),
    ],
    terms=[
        ("brahmacariyaṁ", "&ldquo;the spiritual path&rdquo; &mdash; "
             "the term this discourse's own question concerns, "
             "answered directly with the noble eightfold path"),
        ("brahmacariyapariyosānaṁ", "&ldquo;the culmination of the "
             "spiritual path&rdquo; &mdash; the second half of the "
             "question, answered with the ending of the three roots"),
        ("rāgakkhayo dosakkhayo mohakkhayo", "&ldquo;the ending of "
             "greed, hate, and delusion&rdquo; &mdash; the identical "
             "formula this project's own SN 43 used throughout to "
             "define asaṅkhata"),
        ("ariyo aṭṭhaṅgiko maggo", "&ldquo;the noble eightfold "
             "path&rdquo; &mdash; the answer to the first half of "
             "the mendicant's own question"),
        ("aññataro bhikkhu", "&ldquo;a mendicant&rdquo; &mdash; the "
             "unnamed questioner this discourse and its own "
             "immediately following companion, SN 45.7, both share"),
    ],
    text_intro=("The complete discourse. Translation: Bhikkhu Sujato "
        "(CC0, SuttaCentral)."),
    text=[
        ("p", "&sect;1", "sn45.6:1.1-2.4"),
    ],
    quiz=[
        {"q": "What two questions does the unnamed mendicant ask in this discourse?",
         "opts": ["What is the spiritual path, and what is its own culmination?", "How long has the Buddha been teaching, and where was he born?", "Who are the Buddha's own chief disciples?", "What is the correct way to beg for alms?"],
         "correct": 0,
         "expl": "Two questions, answered in immediate succession with no further elaboration."},
        {"q": "What does the Buddha name as the culmination of the spiritual path?",
         "opts": ["The ending of greed, hate, and delusion", "A specific meditative attainment", "Rebirth in a heavenly realm", "Perfect recitation of the scriptures"],
         "correct": 0,
         "expl": "The identical formula this project's own SN 43 used throughout to define \"the unconditioned.\""},
        {"q": "What does the Buddha name as the spiritual path itself?",
         "opts": ["The noble eightfold path", "Serenity and discernment alone", "The five faculties", "Continuous almsgiving"],
         "correct": 0,
         "expl": "This book's own recurring answer, named again here in the plainest possible form."},
    ],
    marginalia=[
        ("A plain question, plainly answered", [
            "what is the path, what is its end —",
            "two sentences, nothing more",
        ]),
        ("A familiar formula returns", [
            "greed, hate, delusion, ended —",
            "SN 43's own definition of the unconditioned",
        ]),
        ("The same goal, different vocabulary", [
            "\"culmination of the spiritual path\" here —",
            "\"the unconditioned\" there",
        ]),
        ("An unnamed questioner, twice", [
            "\"a mendicant\" — no name given —",
            "the same figure returns at SN 45.7",
        ]),
    ],
    further=[
        '<a href="%s/sn45.6/en/sujato" target="_blank" rel="noopener">'
        "Full Sujato translation on SuttaCentral</a> &mdash; with "
        "Pāli alongside, segment by segment."
        % SC,
        "<a href=\"sn-45.5.html\">SN 45.5 &middot; What's the "
        "Goal?</a> &mdash; the previous discourse.",
        "<a href=\"sn-45.7.html\">SN 45.7 &middot; A Mendicant "
        "(2nd)</a> &mdash; the next discourse.",
    ],
)

# --------------------------------------------------------------------------- #
# SN 45.7 — Dutiyaññatarabhikkhusutta
# --------------------------------------------------------------------------- #
page(
    45, 7, "Aññatarabhikkhu", "A Mendicant (2nd)",
    vagga="Avijjāvagga",
    meta_title="SN 45.7 — A Mendicant (2nd) | Ru-Yi Meditation Center",
    meta_desc=(
        "A reading guide, full English text, and self-check quiz for "
        "a two-question exchange linking the removal of greed, hate, "
        "and delusion to extinguishment and to freedom from death. "
        "From Ru-Yi Meditation Center."),
    glance=[
        ("Setting", "Sāvatthī (presumably continuing from SN 45.6)"),
        ("Speakers", "An unnamed mendicant and the Buddha"),
        ("Form", "Two follow-up questions, each answered directly"),
        ("Length", "&lt;1 minute to read"),
        ("Northern parallel", "No individual parallel confirmed by "
                              "this project's own check"),
        ("Difficulty", "&starf;&#9734;&#9734;&#9734;&#9734; &mdash; "
                       "short, two linked definitions"),
    ],
    why=(
        "A mendicant &mdash; unnamed, possibly the same figure as SN "
        "45.6's own questioner &mdash; asks what &ldquo;the removal "
        "of greed, hate, and delusion&rdquo; is a term for, and "
        "receives &ldquo;the element of extinguishment.&rdquo; A "
        "second question follows immediately: what is freedom from "
        "death, and what path leads to it? The same three-root "
        "formula answers both the &ldquo;what is it&rdquo; and the "
        "path question returns, once more, to the eightfold path."
    ),
    guide=[
        ("One formula, three different names across this vagga", [
            "&ldquo;The ending of greed, hate, and delusion&rdquo; "
            "has now named the unconditioned (SN 43, this project's "
            "own earlier saṃyutta), the culmination of the spiritual "
            "path (SN 45.6), the element of extinguishment, and "
            "freedom from death, all within this single vagga "
            "&mdash; confirmed by direct comparison across all four, "
            "the identical three-root ending answering four "
            "differently framed questions.",
        ]),
        ("A path named again, without variation", [
            "Asked for the path leading to freedom from death, the "
            "Buddha names the noble eightfold path once more, "
            "confirming this vagga's own consistent pattern: "
            "whatever the goal is called, the path to it is always "
            "the identical eight factors, never a different "
            "practice tailored to the particular name in use.",
        ]),
    ],
    terms=[
        ("rāgakkhayo dosakkhayo mohakkhayo", "&ldquo;the removal of "
             "greed, hate, and delusion&rdquo; &mdash; the question "
             "this discourse opens with, the same formula met "
             "repeatedly across this vagga under different names"),
        ("nibbānadhātu", "&ldquo;the element of extinguishment&rdquo; "
             "&mdash; the Buddha's own first answer, naming what the "
             "three-root ending is a term for"),
        ("āsavānaṁ khayavacanaṁ", "&ldquo;the ending of "
             "defilements&rdquo; &mdash; a further gloss on the "
             "element of extinguishment"),
        ("amataṁ", "&ldquo;freedom from death&rdquo; &mdash; the "
             "second question's own subject, answered with the "
             "identical three-root formula"),
        ("amatagāmī maggo", "&ldquo;the path that leads to freedom "
             "from death&rdquo; &mdash; answered, as throughout this "
             "vagga, with the noble eightfold path"),
    ],
    text_intro=("The complete discourse. Translation: Bhikkhu Sujato "
        "(CC0, SuttaCentral)."),
    text=[
        ("h3", "First question: the removal of the three roots"),
        ("p", "&sect;1", "sn45.7:1.1-2.6"),
        ("h3", "Second question: freedom from death, and its own "
                "path"),
        ("p", "&sect;2", "sn45.7:3.1-3.7"),
    ],
    quiz=[
        {"q": "What does the Buddha say \"the removal of greed, hate, and delusion\" is a term for?",
         "opts": ["The element of extinguishment", "A specific meditative state", "The noble eightfold path itself", "Old age and death"],
         "correct": 0,
         "expl": "The Buddha's own first answer, with a further gloss identifying it as the ending of defilements."},
        {"q": "How many different names has the identical \"ending of greed, hate, and delusion\" formula answered to across this vagga, by this discourse's own point?",
         "opts": ["Four — the unconditioned, the culmination of the path, extinguishment, and freedom from death", "Only one, this discourse's own", "Two", "Ten"],
         "correct": 0,
         "expl": "Confirmed by direct comparison across SN 43, SN 45.6, and this discourse's own two questions."},
        {"q": "What path does the Buddha name for freedom from death?",
         "opts": ["The noble eightfold path", "A path found only in dreams", "Serenity alone, without discernment", "No path exists to freedom from death"],
         "correct": 0,
         "expl": "This vagga's own consistent pattern: whatever the goal is called, the path is always the identical eight factors."},
    ],
    marginalia=[
        ("One formula, many names", [
            "greed, hate, delusion, ended —",
            "now the fourth name this vagga gives it",
        ]),
        ("Extinguishment, defined", [
            "the element of nibbāna —",
            "the ending of defilements",
        ]),
        ("Freedom from death, the same way", [
            "the identical three-root formula —",
            "answering yet another question",
        ]),
        ("One path, however the goal is named", [
            "the noble eightfold path, again —",
            "no variation across this vagga's own questions",
        ]),
    ],
    further=[
        '<a href="%s/sn45.7/en/sujato" target="_blank" rel="noopener">'
        "Full Sujato translation on SuttaCentral</a> &mdash; with "
        "Pāli alongside, segment by segment."
        % SC,
        "<a href=\"sn-45.6.html\">SN 45.6 &middot; A Mendicant "
        "(1st)</a> &mdash; the previous discourse.",
        "<a href=\"sn-45.8.html\">SN 45.8 &middot; Analysis</a> "
        "&mdash; already published on this site, the next discourse "
        "in this vagga.",
    ],
)

# --------------------------------------------------------------------------- #
# SN 45.9 — Sūkasutta
# --------------------------------------------------------------------------- #
page(
    45, 9, "Sūka", "A Spike",
    vagga="Avijjāvagga",
    meta_title="SN 45.9 — A Spike | Ru-Yi Meditation Center",
    meta_desc=(
        "A reading guide, full English text, and self-check quiz for "
        "the Sūkasutta &mdash; a rice-spike pointing the right or "
        "wrong way, used to explain why right view determines "
        "whether the path can break ignorance at all. From Ru-Yi "
        "Meditation Center."),
    glance=[
        ("Setting", "Sāvatthī"),
        ("Speakers", "The Buddha, addressing the mendicants directly"),
        ("Form", "A physical simile, applied in both directions "
                 "before its own explanation"),
        ("Length", "~1 minute to read"),
        ("Northern parallel", "No individual parallel confirmed by "
                              "this project's own check"),
        ("Difficulty", "&starf;&#9734;&#9734;&#9734;&#9734; &mdash; "
                       "a vivid, everyday image"),
    ],
    why=(
        "A rice or barley spike, its own sharp point ordinarily "
        "capable of piercing skin, is harmless if it happens to be "
        "pointing the wrong way when trodden on &mdash; and the "
        "identical structure holds, the Buddha says, for a "
        "mendicant's own view and development of the path: pointed "
        "the wrong way, it cannot break ignorance no matter how "
        "vigorously pursued; pointed the right way, it can. Direction "
        "matters independently of effort."
    ),
    guide=[
        ("A sharp point, rendered harmless by direction alone", [
            "The spike's own sharpness is not in question either "
            "way &mdash; what determines whether it draws blood is "
            "purely which way it points when trodden on, confirmed "
            "by reading both halves of the simile directly: not a "
            "claim about a blunt versus a sharp spike, but about "
            "orientation alone.",
        ]),
        ("Right view as orientation, not merely content", [
            "&ldquo;A mendicant whose view and development of the "
            "path is pointing the wrong way&rdquo; cannot break "
            "ignorance &ldquo;no matter&rdquo; how the phrase is "
            "read &mdash; the simile locates the problem in "
            "direction, not in the sharpness or vigor of the "
            "practice itself, a distinct emphasis from this vagga's "
            "own SN 45.1, which treated ignorance and knowledge as "
            "what starts a causal chain rather than as a direction "
            "the path itself can point in.",
        ]),
        ("The same eightfold path, once the direction is right", [
            "Asked how a mendicant whose view points the right way "
            "actually breaks ignorance, the answer is, once more, "
            "the eightfold path's own eight factors developed "
            "together &mdash; this vagga's own recurring answer, "
            "here framed as what becomes possible once orientation "
            "itself is correct.",
        ]),
    ],
    terms=[
        ("sūkaṁ", "&ldquo;a spike&rdquo; of rice or barley &mdash; "
             "the simile's own central image"),
        ("micchāpaṇihitaṁ", "&ldquo;pointing the wrong way&rdquo; "
             "&mdash; applied both to the literal spike and to a "
             "mendicant's own view and path-development"),
        ("sammāpaṇihitaṁ", "&ldquo;pointing the right way&rdquo; "
             "&mdash; the reversed condition, under which the spike "
             "may draw blood and the path may break ignorance"),
        ("avijjaṁ padāletvā vijjaṁ uppādetvā nibbānaṁ sacchikareyya",
             "&ldquo;break ignorance, produce knowledge, and realize "
             "extinguishment&rdquo; &mdash; what becomes possible "
             "once view and path-development point the right way"),
        ("diṭṭhisampanno maggabhāvanāsampanno", "&ldquo;whose view "
             "and development of the path is pointing the right "
             "way&rdquo; &mdash; the discourse's own key phrase, "
             "repeated for both directions of the simile"),
    ],
    text_intro=("The complete discourse. Translation: Bhikkhu Sujato "
        "(CC0, SuttaCentral)."),
    text=[
        ("h3", "A spike pointing the wrong way"),
        ("p", "&sect;1", "sn45.9:1.1-1.7"),
        ("h3", "A spike pointing the right way, and why"),
        ("p", "&sect;2", "sn45.9:2.1-3.3"),
    ],
    quiz=[
        {"q": "What determines whether the rice or barley spike in this simile draws blood?",
         "opts": ["Purely which way it points when trodden on, not its own sharpness", "How hard it is trodden on", "The season it was harvested", "Whether it is rice or barley"],
         "correct": 0,
         "expl": "The spike's own sharpness is not in question either way — the simile isolates direction alone."},
        {"q": "What does this simile say about a mendicant whose view points the wrong way?",
         "opts": ["They cannot break ignorance no matter how the path is otherwise pursued", "They will break ignorance eventually with enough effort", "Their view is irrelevant to breaking ignorance", "Only their meditation practice matters, not their view"],
         "correct": 0,
         "expl": "The problem is located in direction, not in the sharpness or vigor of the practice itself."},
        {"q": "What does a mendicant whose view points the right way actually develop, according to this discourse?",
         "opts": ["The noble eightfold path's own eight factors", "A single, unnamed meditative technique", "Nothing further is specified", "A new practice not named elsewhere in this vagga"],
         "correct": 0,
         "expl": "This vagga's own recurring answer, here framed as what becomes possible once orientation is correct."},
    ],
    marginalia=[
        ("A spike, either way sharp", [
            "harmless pointing the wrong way —",
            "the same sharpness, differently oriented",
        ]),
        ("Direction, not vigor", [
            "not how hard the path is pursued —",
            "which way the view itself points",
        ]),
        ("A distinct emphasis from SN 45.1", [
            "there, what starts a chain —",
            "here, which way the path itself points",
        ]),
        ("The same eight factors, once oriented right", [
            "the noble eightfold path, once more —",
            "possible only once direction is correct",
        ]),
    ],
    further=[
        '<a href="%s/sn45.9/en/sujato" target="_blank" rel="noopener">'
        "Full Sujato translation on SuttaCentral</a> &mdash; with "
        "Pāli alongside, segment by segment."
        % SC,
        "<a href=\"sn-45.8.html\">SN 45.8 &middot; Analysis</a> "
        "&mdash; already published on this site, the previous "
        "discourse in this vagga.",
        "<a href=\"sn-45.10.html\">SN 45.10 &middot; With "
        "Nandiya</a> &mdash; the next discourse, closing this vagga.",
    ],
)

# --------------------------------------------------------------------------- #
# SN 45.10 — Nandiyasutta
# --------------------------------------------------------------------------- #
page(
    45, 10, "Nandiya", "With Nandiya",
    vagga="Avijjāvagga",
    meta_title="SN 45.10 — With Nandiya | Ru-Yi Meditation Center",
    meta_desc=(
        "A reading guide, full English text, and self-check quiz for "
        "the Nandiyasutta &mdash; a wanderer's direct question "
        "closing Avijjāvagga, this book's own first vagga. From "
        "Ru-Yi Meditation Center."),
    glance=[
        ("Setting", "Sāvatthī"),
        ("Speakers", "The wanderer Nandiya and the Buddha"),
        ("Form", "A direct question, a direct answer, and a lay "
                 "follower's own closing declaration"),
        ("Length", "&lt;1 minute to read"),
        ("Northern parallel", "No individual parallel confirmed by "
                              "this project's own check"),
        ("Difficulty", "&starf;&#9734;&#9734;&#9734;&#9734; &mdash; "
                       "short, closes this vagga plainly"),
    ],
    why=(
        "The wanderer Nandiya asks how many things, developed and "
        "cultivated, have extinguishment as their &ldquo;target, "
        "destination, and culmination&rdquo; &mdash; a slightly "
        "different framing than this vagga's own earlier questions, "
        "asking not what the path is called but how many things "
        "constitute it. The answer is the familiar eight, and "
        "Nandiya, satisfied, goes for refuge as a lay follower "
        "&ldquo;for life,&rdquo; closing Avijjāvagga, this book's own "
        "first vagga of fourteen."
    ),
    guide=[
        ("A question about number, not name", [
            "&ldquo;How many things&rdquo; is a different question "
            "than this vagga's own earlier &ldquo;what is the "
            "path,&rdquo; confirmed by direct comparison &mdash; "
            "Nandiya's own phrasing (&ldquo;target, destination, and "
            "culmination&rdquo;) is also distinct from the "
            "vocabulary SN 45.5&ndash;7 used, though the answer "
            "itself, the eightfold path's own eight factors, is "
            "identical.",
        ]),
        ("A lifelong commitment, closing the vagga", [
            "Nandiya's own closing declaration &mdash; going for "
            "refuge &ldquo;for life&rdquo; &mdash; closes "
            "Avijjāvagga on a note of settled conviction rather than "
            "further argument, this project's own familiar closing "
            "pattern for a wanderer or outsider satisfied by an "
            "answer.",
        ]),
        ("This vagga's own untranslated close", [
            "Following this discourse's own genuinely translated "
            "content, the root Pāli carries a closing colophon "
            "(&ldquo;Avijjāvaggo paṭhamo,&rdquo; &ldquo;Avijjāvagga "
            "is the first [vagga]&rdquo;) and an untranslated "
            "meta-uddāna naming all ten of this vagga's own "
            "discourses in verse &mdash; described here rather than "
            "quoted, since Sujato's own English leaves this portion "
            "untranslated and this reading guide does not fabricate "
            "content the translation does not supply.",
        ]),
    ],
    terms=[
        ("nibbānaṅgamā... nibbānaparāyanā... nibbānapariyosānā",
             "&ldquo;have extinguishment as their target, "
             "destination, and culmination&rdquo; &mdash; Nandiya's "
             "own threefold framing of the question"),
        ("aṭṭhime... dhammā", "&ldquo;these eight things&rdquo; "
             "&mdash; the Buddha's own answer, naming the eightfold "
             "path's own eight factors by number before listing them"),
        ("upāsakaṁ maṁ... dhāretu ajjatagge pāṇupetaṁ saraṇaṁ gataṁ",
             "&ldquo;may the worthy Gotama remember me as a lay "
             "follower who has gone for refuge for life&rdquo; "
             "&mdash; Nandiya's own closing declaration"),
        ("avijjāvaggo paṭhamo", "&ldquo;Avijjāvagga is the first "
             "[vagga]&rdquo; &mdash; this vagga's own closing "
             "colophon, left untranslated in the root and described "
             "rather than quoted as English here"),
        ("tassuddānaṁ", "&ldquo;its own summary verse&rdquo; "
             "&mdash; the heading introducing the untranslated "
             "meta-uddāna naming all ten of this vagga's own "
             "discourses"),
    ],
    text_intro=("The complete genuinely translated content of the "
        "discourse. This vagga's own closing colophon and "
        "meta-uddāna are left untranslated in the source and are "
        "described, not quoted, above. Translation: Bhikkhu Sujato "
        "(CC0, SuttaCentral)."),
    text=[
        ("p", "&sect;1", "sn45.10:1.1-2.7"),
    ],
    quiz=[
        {"q": "How does Nandiya's own question differ in framing from this vagga's earlier ones?",
         "opts": ["He asks how many things have extinguishment as their target, rather than what the path is called", "He asks about a completely different topic", "He disputes that a path exists at all", "He asks only about the definition of ignorance"],
         "correct": 0,
         "expl": "A different question, though the answer — the eightfold path's own eight factors — is identical to what this vagga has given throughout."},
        {"q": "How does Nandiya respond to the Buddha's own answer?",
         "opts": ["He goes for refuge as a lay follower \"for life\"", "He disputes the answer", "He asks for further clarification before accepting it", "He leaves without responding"],
         "correct": 0,
         "expl": "A note of settled conviction closing the vagga, this project's own familiar pattern for an outsider satisfied by an answer."},
        {"q": "What does this discourse's own closing colophon, left untranslated in the root, announce?",
         "opts": ["That Avijjāvagga is the first vagga of this saṃyutta, with a meta-uddāna naming all ten of its discourses", "The opening of a second saṃyutta", "A cross-reference to Book IV", "Nothing further; the vagga ends without any closing marker"],
         "correct": 0,
         "expl": "Described rather than quoted, since Sujato's own English leaves this portion untranslated."},
    ],
    marginalia=[
        ("A different question, the same answer", [
            "\"how many things\" — not \"what is it called\" —",
            "the eightfold path, once again",
        ]),
        ("A lifelong commitment", [
            "\"for life\" — refuge taken —",
            "closing on settled conviction",
        ]),
        ("A vagga's own quiet close", [
            "\"Avijjāvagga is the first\" —",
            "left untranslated, described not invented",
        ]),
        ("Ten discourses complete", [
            "causation, friendship, chariot, catechisms, spike —",
            "thirteen more vaggas still ahead in this saṃyutta",
        ]),
    ],
    further=[
        '<a href="%s/sn45.10/en/sujato" target="_blank" rel="noopener">'
        "Full Sujato translation on SuttaCentral</a> &mdash; with "
        "Pāli alongside, segment by segment."
        % SC,
        "<a href=\"sn-45.9.html\">SN 45.9 &middot; A Spike</a> "
        "&mdash; the previous discourse.",
        "<a href=\"sn-55.1.html\">SN 55.1 &middot; A Wheel-Turning "
        "Monarch</a> &mdash; already published on this site, "
        "standing ahead of this project's next vagga, Vihāravagga "
        "(SN 45.11&ndash;20), not yet built.",
    ],
)
