#!/usr/bin/env python3
"""
Keep the Ru-Yi top bar on the standalone (non-Jekyll) pages in sync with the
shared one.

The reading pages under discourses/ (and a few others) are authored as complete
standalone HTML documents with their own self-contained design, so they cannot
use _includes/header.html. Instead they carry an inlined copy of the bar. This
script is the single place that copy is defined: edit CANONICAL_CSS / HEADER /
DRAWER here and re-run, never hand-edit the pages.

Unlike the older scripts/add_topbar.py (which only ever added a bar to pages
that had none), this REPLACES whatever bar is already there, so the copy can be
corrected after the fact. It is idempotent: running it twice changes nothing.

  python3 scripts/sync_topbar.py            # dry run, reports what would change
  python3 scripts/sync_topbar.py --apply    # write the changes
  python3 scripts/sync_topbar.py --limit 3 --apply   # first 3 files only

position:static is deliberate. These pages have their own sticky elements (the
.tabs bar on a discourse page); a sticky header would stack on top of them.
Log In / Sign Up are deliberately absent too — they are not on these pages
today, they would widen the bar by ~164px, and the cross-domain session script
that drives them is not loaded here.
"""
import os, re, sys, io

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Directories skipped entirely. visuddhimagga/ at the repo root is an orphaned
# earlier draft — nothing links to it; theravada/visuddhimagga/ is the live one.
SKIP_DIRS = {'_site', '.git', 'node_modules', '.jekyll-cache', 'scripts',
             '_layouts', '_includes', 'visuddhimagga'}

BASE_STATIC = (".site-header{background:#fff;border-bottom:1px solid #e7e7ea;"
               "position:static;font-family:'Inter',sans-serif;}")
BASE_STICKY = (".site-header{background:rgba(255,255,255,.94);"
               "backdrop-filter:saturate(180%) blur(10px);"
               "-webkit-backdrop-filter:saturate(180%) blur(10px);"
               "border-bottom:1px solid #e7e7ea;position:sticky;top:0;z-index:100;"
               "font-family:'Inter',sans-serif;}")

CANONICAL_CSS = '''<style id="ruyi-topbar">
/* Canonical Ru-Yi top bar for standalone pages. Generated by
   scripts/sync_topbar.py — do not hand-edit; edit the script and re-run.
   Scoped under .site-header so it cannot reach the host page's own styles.
   position:static so it never fights these pages' sticky .tabs bar. */
__BASE__
.site-header *{box-sizing:border-box;}
.site-header .header-inner{max-width:1280px;margin:0 auto;padding:0 56px;display:flex;align-items:center;justify-content:space-between;min-height:72px;gap:32px;}
.site-header .brand{display:inline-flex;align-items:center;gap:12px;text-decoration:none;color:inherit;}
.site-header .brand:hover{text-decoration:none;}
.site-header .brand-logo{height:44px;width:44px;display:block;flex-shrink:0;}
.site-header .brand-name{font-family:'Playfair Display',serif;font-size:19px;font-weight:500;color:#1a1a1a;letter-spacing:.005em;line-height:1.1;}
.site-header .brand-name em{display:block;font-style:italic;font-weight:400;color:#559986;font-size:12px;letter-spacing:.18em;text-transform:uppercase;margin-top:2px;}
.site-header .site-nav{display:flex;gap:32px;}
.site-header .site-nav a{font-size:15px;font-weight:500;color:#4a4d53;text-decoration:none;letter-spacing:.01em;padding:4px 0;position:relative;}
.site-header .site-nav a:hover{color:#8c2f12;text-decoration:none;}
.site-header .site-nav a.active{color:#1a1a1a;}
.site-header .site-nav a.active::after{content:"";position:absolute;left:0;right:0;bottom:-22px;height:2px;background:#b8431c;}
.site-header .header-actions{display:flex;align-items:center;gap:8px;}
.site-header .nav-hamburger{display:none;flex-direction:column;justify-content:center;align-items:center;gap:5px;width:40px;height:40px;background:none;border:none;cursor:pointer;padding:8px;border-radius:8px;-webkit-tap-highlight-color:transparent;}
.site-header .nav-hamburger span{display:block;width:22px;height:2px;background:#2a2a2a;border-radius:2px;transition:transform .28s cubic-bezier(.22,.61,.36,1),opacity .2s;transform-origin:center;}
.site-header .nav-hamburger.is-open span:nth-child(1){transform:translateY(7px) rotate(45deg);}
.site-header .nav-hamburger.is-open span:nth-child(2){opacity:0;transform:scaleX(0);}
.site-header .nav-hamburger.is-open span:nth-child(3){transform:translateY(-7px) rotate(-45deg);}
/* Same three stages as assets/css/style.css, so the bar behaves identically
   wherever the reader happens to be. This bar needs about 1079px at full size
   (brand 217 + nav 560 + search 126 + gaps + padding); before these rules the
   links wrapped to two lines from there down and overflowed outright at 768. */
@media (max-width:1279px){.site-header .header-inner{padding:0 24px;gap:18px;}.site-header .site-nav{gap:20px;}.site-header .nav-search-label,.site-header .nav-search-btn kbd{display:none;}}
@media (max-width:1060px){.site-header .brand-name em{display:none;}.site-header .site-nav{gap:15px;}.site-header .site-nav a{font-size:14px;}}
@media (max-width:940px){.site-header .header-inner{padding:0 24px;min-height:64px;gap:0;}.site-header .brand-name em{display:none;}.site-header .site-nav{display:none;}.site-header .nav-hamburger{display:flex;}.site-header .nav-search-label,.site-header .nav-search-btn kbd{display:none;}}
@media (max-width:720px){.site-header .header-inner{padding:0 20px;}}
/* The drawer sits outside .site-header, so these few rules are unscoped. No
   standalone page defines these class names — checked before adding them. */
.mobile-nav-drawer{display:none;}
@media (max-width:940px){
.mobile-nav-drawer{display:block;position:fixed;top:64px;left:0;right:0;bottom:0;background:#fff;z-index:9999;overflow-y:auto;transform:translateY(-12px);opacity:0;pointer-events:none;transition:opacity .22s ease,transform .22s cubic-bezier(.22,.61,.36,1);}
.mobile-nav-drawer.is-open{opacity:1;transform:translateY(0);pointer-events:auto;}
.mobile-nav-drawer nav{display:flex;flex-direction:column;padding:8px 0 48px;}
.mobile-nav-drawer nav a{font-size:18px;font-weight:500;padding:18px 28px;border-bottom:1px solid #f0f0f0;text-decoration:none;letter-spacing:.06em;text-transform:uppercase;color:#1a1a1a;display:block;}
.mobile-nav-drawer nav a.active{color:#b8431c;}
.mobile-nav-drawer nav a:hover{color:#b8431c;background:#fdf6f3;}
}
body.nav-overlay-open{overflow:hidden;}
</style>
'''

NAV = [('/', 'Home'), ('/about/', 'About'), ('/columns/', 'Columns'),
       ('/dharma/', 'Dharma'), ('/english-school/', 'English School'),
       ('/community/', 'Community')]


def nav_links(active, indent):
    return '\n'.join(
        f'{indent}<a href="{h}"{' class="active"' if h == active else ''}>{t}</a>'
        for h, t in NAV)

HEADER_TPL = '''<header class="site-header">
  <div class="header-inner">
    <a href="/" class="brand">
      <img src="/logos/ruyi-logo-green.png" alt="Ru-Yi Meditation Center" class="brand-logo">
      <span class="brand-name">Ru-Yi <em>Meditation Center</em></span>
    </a>
    <nav class="site-nav" aria-label="Primary">
__NAV6__
    </nav>
    <div class="header-actions">
      <button type="button" class="nav-search-btn" id="siteSearchBtn" aria-label="Search this site" title="Search (press /)"><svg viewBox="0 0 24 24" width="17" height="17" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><circle cx="11" cy="11" r="7"/><line x1="21" y1="21" x2="16.5" y2="16.5"/></svg><span class="nav-search-label">Search</span><kbd>/</kbd></button>
      <button type="button" class="nav-hamburger" id="navHamburger" aria-label="Open menu" aria-expanded="false"><span></span><span></span><span></span></button>
    </div>
  </div>
</header>'''

DRAWER_TPL = '''<div class="mobile-nav-drawer" id="mobileNavDrawer" aria-hidden="true">
  <nav aria-label="Mobile navigation">
__NAV6__
  </nav>
</div>
<script id="ruyi-topbar-js">(function(){var b=document.getElementById('navHamburger'),d=document.getElementById('mobileNavDrawer');if(!b||!d)return;function openMenu(){d.classList.add('is-open');d.setAttribute('aria-hidden','false');b.classList.add('is-open');b.setAttribute('aria-expanded','true');document.body.classList.add('nav-overlay-open');}function closeMenu(){d.classList.remove('is-open');d.setAttribute('aria-hidden','true');b.classList.remove('is-open');b.setAttribute('aria-expanded','false');document.body.classList.remove('nav-overlay-open');}b.addEventListener('click',function(e){e.stopPropagation();d.classList.contains('is-open')?closeMenu():openMenu();});document.addEventListener('click',function(e){if(d.classList.contains('is-open')&&!d.contains(e.target)&&!b.contains(e.target))closeMenu();});})();</script>'''

ACTIVE_RE = re.compile(r'<a href="([^"]+)"[^>]*class="active"')
STICKY_RE = re.compile(r'\.site-header\s*{[^}]*position\s*:\s*sticky', re.S)


def detect(text):
    """Preserve what the page already declares: which nav item is active, and
    whether its bar is sticky. Reading pages are static (their .tabs bar is
    sticky); section pages like english-school are sticky and stay that way."""
    m = ACTIVE_RE.search(text)
    active = m.group(1) if m else '/dharma/'
    return active, ('sticky' if STICKY_RE.search(text) else 'static')


def build(active, position):
    css = CANONICAL_CSS.replace('__BASE__', BASE_STICKY if position == 'sticky' else BASE_STATIC)
    header = HEADER_TPL.replace('__NAV6__', nav_links(active, '      '))
    drawer = DRAWER_TPL.replace('__NAV6__', nav_links(active, '      '))
    return css, header, drawer


CSS_RE    = re.compile(r'<style id="ruyi-topbar">.*?</style>\n?', re.S)
HEADER_RE = re.compile(r'<header class="site-header">.*?</header>', re.S)
DRAWER_RE = re.compile(r'\n?<div class="mobile-nav-drawer".*?</div>\s*<script id="ruyi-topbar-js">.*?</script>', re.S)


def targets():
    out = []
    for dp, dn, fn in os.walk(REPO):
        dn[:] = [d for d in dn if d not in SKIP_DIRS and not d.startswith('.')]
        for f in sorted(fn):
            if not f.endswith('.html'):
                continue
            p = os.path.join(dp, f)
            t = io.open(p, encoding='utf-8', errors='replace').read()
            if t.lstrip().startswith('---'):
                continue                      # Jekyll page: uses the include
            if '<header class="site-header">' not in t:
                continue                      # not a bar-carrying standalone page
            out.append(p)
    return sorted(out)


def dedupe(text):
    """A handful of Sutta Nipata pages were injected twice at some point and
    carry two <body> tags and two identical headers. Keep the first of each."""
    hdrs = list(HEADER_RE.finditer(text))
    if len(hdrs) <= 1:
        return text
    out = text
    for m in reversed(hdrs[1:]):
        start, end = m.start(), m.end()
        stray = re.search(r'<body[^>]*>\s*$', out[:start])   # the stray <body> too
        if stray:
            start = stray.start()
        out = out[:start] + out[end:]
    return out


def sync(text):
    """Return the page with a canonical bar, or None if nothing would change."""
    if not HEADER_RE.search(text):
        return None
    active, position = detect(text)
    css, header, drawer = build(active, position)
    new = dedupe(text)
    new = DRAWER_RE.sub('', new)                        # drop any previous drawer
    if CSS_RE.search(new):
        new = CSS_RE.sub(lambda m: css, new, count=1)
    elif '</head>' in new:
        # A few section pages (english-school) hand-rolled their bar without the
        # marker block. Their old rules stay where they are but are unscoped and
        # earlier in the document, so this scoped block placed last wins.
        new = new.replace('</head>', css + '</head>', 1)
    else:
        return None
    new = HEADER_RE.sub(lambda m: header + '\n' + drawer, new, count=1)
    return None if new == text else new


if __name__ == '__main__':
    apply = '--apply' in sys.argv
    limit = None
    if '--limit' in sys.argv:
        limit = int(sys.argv[sys.argv.index('--limit') + 1])
    files = targets()
    if limit:
        files = files[:limit]
    changed = skipped = 0
    for p in files:
        t = io.open(p, encoding='utf-8', errors='replace').read()
        new = sync(t)
        if new is None:
            skipped += 1
            continue
        changed += 1
        if apply:
            io.open(p, 'w', encoding='utf-8').write(new)
    verb = 'updated' if apply else 'would update'
    print(f'{len(files)} bar-carrying standalone pages found')
    print(f'  {verb}: {changed}')
    print(f'  already canonical: {skipped}')
    if not apply:
        print('\n(dry run — pass --apply to write)')
